/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Outros;

import Principal.PrincipalTelaInterna;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author silen
 */
public class DiscordTelaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form DiscordTelaInterna
     */
    public DiscordTelaInterna() {
        initComponents();
        this.setResizable(false); //Deixa a tela fixa.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        discordPainel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        botaoFecharDiscord = new javax.swing.JButton();
        botaoDiscordInterno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        discordPainel.setBackground(new java.awt.Color(0, 0, 255));
        discordPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Discord do Projeto, para quem quer bater papo sobre jogos de celular");
        discordPainel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        botaoFecharDiscord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoFecharDiscord.setText("FECHAR");
        botaoFecharDiscord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharDiscordActionPerformed(evt);
            }
        });
        discordPainel.add(botaoFecharDiscord, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        botaoDiscordInterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoDiscordInterno.setText("DISCORD");
        botaoDiscordInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDiscordInternoActionPerformed(evt);
            }
        });
        discordPainel.add(botaoDiscordInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 210, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/discord icon.png"))); // NOI18N
        discordPainel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 130, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discordPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(discordPainel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharDiscordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharDiscordActionPerformed
        PrincipalTelaInterna principalTela = new PrincipalTelaInterna(); 
        principalTela.setVisible(true); 
        getParent().add(principalTela); 
        this.dispose(); 
    }//GEN-LAST:event_botaoFecharDiscordActionPerformed

    private void botaoDiscordInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDiscordInternoActionPerformed
        String[] args;
        try{
            URI link = new URI("https://discord.gg/MgHGFpnt6N");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botaoDiscordInternoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoDiscordInterno;
    public static javax.swing.JButton botaoFecharDiscord;
    private javax.swing.JDesktopPane discordPainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
