/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Outros;

import Principal.PrincipalTelaInterna;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author Bruno Pz
 */
public class RankingTelaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form RankingTelaInterna
     */
    public RankingTelaInterna() {
        initComponents();
        this.setResizable(false); //Deixa a tela fixa.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rankingPainel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoFecharRanking = new javax.swing.JButton();
        botaoRankingInterno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        rankingPainel.setBackground(new java.awt.Color(0, 153, 255));
        rankingPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ranking Melhores Jogos 2023 segundo Tom's Guides: ");
        rankingPainel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 26, 474, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Detalhe: alguns sites em inglês. Utilize o Google Tradutor.");
        rankingPainel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        botaoFecharRanking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoFecharRanking.setText("FECHAR");
        botaoFecharRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharRankingActionPerformed(evt);
            }
        });
        rankingPainel.add(botaoFecharRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        botaoRankingInterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRankingInterno.setText("Ranking Melhores Jogos em 7 Categorias");
        botaoRankingInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRankingInternoActionPerformed(evt);
            }
        });
        rankingPainel.add(botaoRankingInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 350, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/galaga 128.png"))); // NOI18N
        rankingPainel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rankingPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rankingPainel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRankingInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRankingInternoActionPerformed
        String[] args;
        try{
            URI link = new URI("https://www.tomsguide.com/round-up/best-android-games");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botaoRankingInternoActionPerformed

    private void botaoFecharRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharRankingActionPerformed
        PrincipalTelaInterna principalTela = new PrincipalTelaInterna(); 
        principalTela.setVisible(true); 
        getParent().add(principalTela); 
        this.dispose(); 
    }//GEN-LAST:event_botaoFecharRankingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoFecharRanking;
    public static javax.swing.JButton botaoRankingInterno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JDesktopPane rankingPainel;
    // End of variables declaration//GEN-END:variables
}
