/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Outros;

import Principal.PrincipalTelaInterna;
import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author silen
 */
public class SobreTelaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form SobreTelaInterna
     */
    public SobreTelaInterna() {
        initComponents();
        this.setResizable(false); //Deixa a tela fixa.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sobrePainel = new javax.swing.JDesktopPane();
        botaoFecharInterno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botaoSobreInterno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botaoSecitecInterno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        sobrePainel.setBackground(new java.awt.Color(255, 255, 0));
        sobrePainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoFecharInterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoFecharInterno.setText("FECHAR");
        botaoFecharInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharInternoActionPerformed(evt);
            }
        });
        sobrePainel.add(botaoFecharInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Saiba mais sobre o dev deste Projeto:");
        sobrePainel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        botaoSobreInterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSobreInterno.setText("Dev Bruno, Aluno Secitec");
        botaoSobreInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobreInternoActionPerformed(evt);
            }
        });
        sobrePainel.add(botaoSobreInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 320, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Conhece o Secitec? Saiba mais sobre a Escola e seus cursos: ");
        sobrePainel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        botaoSecitecInterno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSecitecInterno.setText("SECITEC");
        botaoSecitecInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSecitecInternoActionPerformed(evt);
            }
        });
        sobrePainel.add(botaoSecitecInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 320, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/Secitec logo.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        sobrePainel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 470, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sobrePainel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sobrePainel, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharInternoActionPerformed
        PrincipalTelaInterna principalTela = new PrincipalTelaInterna(); 
        principalTela.setVisible(true); 
        getParent().add(principalTela); 
        this.dispose(); 
    }//GEN-LAST:event_botaoFecharInternoActionPerformed

    private void botaoSobreInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreInternoActionPerformed
        String[] args;
        try{
            URI link = new URI("https://www.linkedin.com/in/bruno-c-perez-a712b0276/");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botaoSobreInternoActionPerformed

    private void botaoSecitecInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSecitecInternoActionPerformed
        String[] args;
        try{
            URI link = new URI("https://www.secitec.mt.gov.br/");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_botaoSecitecInternoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoFecharInterno;
    public static javax.swing.JButton botaoSecitecInterno;
    public static javax.swing.JButton botaoSobreInterno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JDesktopPane sobrePainel;
    // End of variables declaration//GEN-END:variables
}
