/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Principal;

/**
 *
 * @author Bruno Pz
 * Aqui contém os jogos que pesquisei e que são uma indicação para usuários
 * adultos, que se sentem desnorteados com os muitos jogos da Play Store. Também
 * tem: Tela Sobre (sobre meu estudo), Tela de Ranking (Top 10 Jogos 2023), Produ-
 * toras (Empresas como Supercell e outras muito poderosas nos jogos mobile) 
 * além de funções que o senhor nos ensinou durante as aulas professor.
 */
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import Conexao.Conexao;
import DAO.Categoria;

import DAO.DAO;
import DAO.Jogos;
import DAO.Joguim;
import Outros.DiscordTelaInterna;
import Outros.ProdutorasTelaInterna;
import Outros.RankingTelaInterna;
import Outros.SobreTelaInterna;
import Login.TelaLogin;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.FileOutputStream;

import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
//import java.util.Map;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.text.Document;

public class PrincipalTelaInterna extends javax.swing.JInternalFrame {
    
    
    
    public PrincipalTelaInterna() {
        initComponents();
        
        this.setResizable(false); //Deixa a tela fixa.
        //getCategoria();
        DefaultTableModel model = (DefaultTableModel) campoTabelaPrincipal.getModel();
        campoTabelaPrincipal.setRowSorter(new TableRowSorter(model));

        readJTable();
        setarData();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        principalPainel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoTabelaPrincipal = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNomeJogo = new javax.swing.JTextField();
        botaoBuscarJogo = new javax.swing.JButton();
        botaoMostrarTudo = new javax.swing.JButton();
        campoCategoriaInterna = new javax.swing.JTextField();
        botaoBuscarCategoria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rotuloData = new javax.swing.JLabel();
        botaoRelatorio = new javax.swing.JButton();
        botaoRanking = new javax.swing.JButton();
        botaoProdutoras = new javax.swing.JButton();
        botaoDiscord = new javax.swing.JButton();
        botaoSobre = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoListaCategorias = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        principalPainel.setBackground(new java.awt.Color(204, 204, 204));
        principalPainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Elenca Jogos 2023");
        principalPainel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/android logo colored.png"))); // NOI18N
        principalPainel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 50, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/android.png"))); // NOI18N
        principalPainel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 140, 130));

        campoTabelaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jogo", "Nota", "Produtora", "Classificação", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        campoTabelaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoTabelaPrincipalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(campoTabelaPrincipal);

        principalPainel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 187, 780, 240));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Digite uma categoria de 1 a 10: ");
        principalPainel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Digite o nome do jogo: ");
        principalPainel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        campoNomeJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeJogoActionPerformed(evt);
            }
        });
        campoNomeJogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNomeJogoKeyTyped(evt);
            }
        });
        principalPainel.add(campoNomeJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, -1));

        botaoBuscarJogo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoBuscarJogo.setText("BUSCAR");
        botaoBuscarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarJogoActionPerformed(evt);
            }
        });
        principalPainel.add(botaoBuscarJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 100, -1));

        botaoMostrarTudo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoMostrarTudo.setText("MOSTRAR TUDO");
        botaoMostrarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMostrarTudoActionPerformed(evt);
            }
        });
        principalPainel.add(botaoMostrarTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 150, -1));

        campoCategoriaInterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCategoriaInternaActionPerformed(evt);
            }
        });
        campoCategoriaInterna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCategoriaInternaKeyTyped(evt);
            }
        });
        principalPainel.add(campoCategoriaInterna, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 140, -1));

        botaoBuscarCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoBuscarCategoria.setText("BUSCAR CATEGORIA");
        botaoBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarCategoriaActionPerformed(evt);
            }
        });
        principalPainel.add(botaoBuscarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        rotuloData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotuloData, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rotuloData, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        principalPainel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 780, 80));

        botaoRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRelatorio.setText("RELATÓRIO");
        botaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioActionPerformed(evt);
            }
        });
        principalPainel.add(botaoRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        botaoRanking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoRanking.setText("RANKING");
        botaoRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRankingActionPerformed(evt);
            }
        });
        principalPainel.add(botaoRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        botaoProdutoras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoProdutoras.setText("PRODUTORAS");
        botaoProdutoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutorasActionPerformed(evt);
            }
        });
        principalPainel.add(botaoProdutoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        botaoDiscord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoDiscord.setText("DISCORD");
        botaoDiscord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDiscordActionPerformed(evt);
            }
        });
        principalPainel.add(botaoDiscord, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        botaoSobre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSobre.setText("SOBRE");
        botaoSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSobreActionPerformed(evt);
            }
        });
        principalPainel.add(botaoSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        botaoSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoSair.setText("SAIR");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });
        principalPainel.add(botaoSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        botaoListaCategorias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoListaCategorias.setText("CATEGORIAS");
        botaoListaCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListaCategoriasActionPerformed(evt);
            }
        });
        principalPainel.add(botaoListaCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalPainel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principalPainel, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarJogoActionPerformed
        readJTableForJogo(campoNomeJogo.getText());
    }//GEN-LAST:event_botaoBuscarJogoActionPerformed

    private void campoTabelaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoTabelaPrincipalMouseClicked
        if (campoTabelaPrincipal.getSelectedRow() != -1) {
            campoNomeJogo.setText(campoTabelaPrincipal.getValueAt
        (campoTabelaPrincipal.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_campoTabelaPrincipalMouseClicked

    private void botaoMostrarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMostrarTudoActionPerformed
                readJTable();
    }//GEN-LAST:event_botaoMostrarTudoActionPerformed

    private void botaoBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarCategoriaActionPerformed
        String texto = campoCategoriaInterna.getText();
        try {
            int numero = Integer.parseInt(texto);
            readJTableForCategoria(numero);
        } catch (NumberFormatException e) {
            System.out.println("Por favor, insira um número válido.");
        }
    }//GEN-LAST:event_botaoBuscarCategoriaActionPerformed

    private void campoNomeJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeJogoActionPerformed

    private void campoCategoriaInternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCategoriaInternaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCategoriaInternaActionPerformed

    private void campoNomeJogoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeJogoKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            JOptionPane.showMessageDialog(null, "Por favor, "
                    + "digite apenas letras.");
            evt.consume();
        }
    }//GEN-LAST:event_campoNomeJogoKeyTyped

    private void campoCategoriaInternaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCategoriaInternaKeyTyped
        char d = evt.getKeyChar();
        if (Character.isLetter(d)) {
            JOptionPane.showMessageDialog(null, "Por favor, "
                    + "digite apenas números de 1 a 10.");
            evt.consume();
        }
    }//GEN-LAST:event_campoCategoriaInternaKeyTyped

    private void botaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatorioActionPerformed
        gerarPDF();
    }//GEN-LAST:event_botaoRelatorioActionPerformed

    private void botaoListaCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListaCategoriasActionPerformed
        String categorias = "1 - estrategia\n" +
                                    "2 - acao\n" +
                                    "3 - esporte\n" +
                                    "4 - tabuleiro\n" +
                                    "5 - cartas\n" +
                                    "6 - casual\n" +
                                    "7 - simulacao\n" +
                                    "8 - corrida\n" +
                                    "9 - arcade\n" +
                                    "10 - rpg";
                                    
                JOptionPane.showMessageDialog(null, categorias);
    }//GEN-LAST:event_botaoListaCategoriasActionPerformed

    private void botaoRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRankingActionPerformed
        RankingTelaInterna rankingTela = new RankingTelaInterna(); 
        rankingTela.setVisible(true); 
        getParent().add(rankingTela); 
        this.dispose();
    }//GEN-LAST:event_botaoRankingActionPerformed

    private void botaoProdutorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutorasActionPerformed
        ProdutorasTelaInterna produtorasTela = new ProdutorasTelaInterna(); 
        produtorasTela.setVisible(true); 
        getParent().add(produtorasTela); 
        this.dispose(); 
    }//GEN-LAST:event_botaoProdutorasActionPerformed

    private void botaoDiscordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDiscordActionPerformed
        DiscordTelaInterna discordTela = new DiscordTelaInterna(); 
        discordTela.setVisible(true); 
        getParent().add(discordTela); 
        this.dispose(); 
    }//GEN-LAST:event_botaoDiscordActionPerformed

    private void botaoSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSobreActionPerformed
        SobreTelaInterna sobreTela = new SobreTelaInterna(); 
        sobreTela.setVisible(true); 
        getParent().add(sobreTela); 
        this.dispose(); 
    }//GEN-LAST:event_botaoSobreActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoBuscarCategoria;
    public static javax.swing.JButton botaoBuscarJogo;
    public static javax.swing.JButton botaoDiscord;
    public static javax.swing.JButton botaoListaCategorias;
    public static javax.swing.JButton botaoMostrarTudo;
    public static javax.swing.JButton botaoProdutoras;
    public static javax.swing.JButton botaoRanking;
    public static javax.swing.JButton botaoRelatorio;
    public static javax.swing.JButton botaoSair;
    public static javax.swing.JButton botaoSobre;
    public static javax.swing.JTextField campoCategoriaInterna;
    public static javax.swing.JTextField campoNomeJogo;
    public static javax.swing.JTable campoTabelaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JDesktopPane principalPainel;
    public static javax.swing.JLabel rotuloData;
    // End of variables declaration//GEN-END:variables
    
    private void readJTable() {
            DefaultTableModel modelo = (DefaultTableModel) campoTabelaPrincipal.
                    getModel();
            modelo.setNumRows(0);
            DAO vdao = new DAO();

            for (Jogos v : vdao.getJogos()) {

                modelo.addRow(new Object[]{
                    v.getId(),
                    v.getJogo(),
                    v.getNota(),
                    v.getProdutora(),
                    v.getClassificacao(),
                    v.getCategoria_id(),
                });

            }
    }
    
    public void readJTableForJogo(String jogo) {
            DefaultTableModel model = (DefaultTableModel) campoTabelaPrincipal.
                    getModel();
            model.setNumRows(0);
            DAO vdao = new DAO();

            for (Jogos v : vdao.readForJogo(jogo)) {
                model.addRow(new Object[]{
                    v.getId(),
                    v.getJogo(),
                    v.getNota(),
                    v.getProdutora(),
                    v.getClassificacao(),
                    v.getCategoria_id(),
                });
           }
    } 
    
    public void readJTableForCategoria(int categoria_id) {
        
        DefaultTableModel model = (DefaultTableModel) campoTabelaPrincipal.getModel();
        model.setNumRows(0);
        DAO vdao = new DAO();

        for (Categoria v : vdao.readForCategoria(categoria_id)) {
            model.addRow(new Object[]{
                v.getId(),
                v.getJogo(),
                v.getNota(),
                v.getProdutora(),
                v.getClassificacao(),
                v.getCategoria_id(),
            });
        }
    }
    
    private void setarData() {
        
        Date datinha = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
        rotuloData.setText(formatador.format(datinha));
    }
    
    private void gerarPDF(){
        
        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        
        try {
            PdfWriter.getInstance(document, new FileOutputStream("jogos.pdf"));
            document.open();
            Date datinha = new Date();
            DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
            document.add(new Paragraph(formatador.format(datinha)));
            document.add(new Paragraph("Listagem de jogos:"));
            document.add(new Paragraph(" "));
            PdfPTable tabela = new PdfPTable(6); 
            PdfPCell col0 = new PdfPCell(new Paragraph("ID")); 
            tabela.addCell(col0);
            PdfPCell col1 = new PdfPCell(new Paragraph("Jogo"));
            tabela.addCell(col1);
            PdfPCell col2 = new PdfPCell(new Paragraph("Nota"));        
            tabela.addCell(col2);
            PdfPCell col3 = new PdfPCell(new Paragraph("Produtora"));
            tabela.addCell(col3);
            PdfPCell col4 = new PdfPCell(new Paragraph("Classificação"));
            tabela.addCell(col4);
            PdfPCell col5 = new PdfPCell(new Paragraph("Categoria ID"));
            tabela.addCell(col5);

            try {
                Connection con = Conexao.getConnection();
                PreparedStatement stmt = null;
                ResultSet rs = null;
                stmt =  con.prepareStatement("SELECT * FROM jogos ORDER BY id");
                rs = stmt.executeQuery();
                while (rs.next()) {
                    tabela.addCell(String.valueOf(rs.getInt("id"))); // Adicione o ID à tabela
                    tabela.addCell(rs.getString("jogo"));
                    tabela.addCell(String.valueOf(rs.getDouble("nota")));
                    tabela.addCell(rs.getString("produtora"));
                    tabela.addCell(rs.getString("classificacao"));
                    tabela.addCell(String.valueOf(rs.getInt("categoria_id")));
                }
                Conexao.closeConnection(con, stmt, rs);

            } catch (Exception ex) {
                System.out.println(ex);
            }
            document.add(tabela);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            document.close();
        }

        try {
            Desktop.getDesktop().open(new File("jogos.pdf"));
        } catch (Exception e2) {
            System.out.println(e2);
        }
    }

}
